parameters:
  flavor: t1.small
  image: centos72 
  key_name: mac-2
  router: R1
  external_network: internet
  vrrp_subnet_cidr: 10.250.0.0/24
  vrrp_subnet_dns: 8.8.8.8
  haproxy_ports: "80,443"
  dmz_subnet_cidr: 10.0.0.0/24
